WIP: taget factory for splitting raster into tiles
njtierney/geotargets pull request #76
Opened 2024-05-22 00:39 UTC by Aariq

I took a shot at creating a `tar_terra_tiles()` which is a target factory that creates two targets:
1) an upstream target that takes a SpatRaster and a template to define the tiles (the `y` argument of `terra::makeTiles()`), splits the raster into tiles, saves them to disk, and returns a vector of file paths.
2) a downstream target that maps over the file paths in the upstream target and reads them in as rasters using dynamic branching.

This downstream target is then ready to use in further targets with `pattern = "map"`.

Unfortunately, it isn't quite working yet, but here's an example anyway:

``` r
library(targets)
library(geotargets)

tar_terra_tiles(
    name = rast_split,
    raster = my_map,
    template = terra::rast(ncols = 2, nrows = 2),
    tiles_dir = "tiles_test"
)
#> $rast_split_tile
#> <tar_stem> 
#>   name: rast_split_tile 
#>   description:  
#>   command:
#>     make_tiles(raster = raster, template = template, tiles_dir = tiles_dir, 
#>         name_tiles = name_tiles, filetype = filetype, gdal = gdal) 
#>   format: file 
#>   repository: local 
#>   iteration method: vector 
#>   error mode: stop 
#>   memory mode: persistent 
#>   storage mode: main 
#>   retrieval mode: main 
#>   deployment mode: worker 
#>   priority: 0 
#>   resources:
#>     list() 
#>   cue:
#>     mode: always
#>     command: TRUE
#>     depend: TRUE
#>     format: TRUE
#>     repository: TRUE
#>     iteration: TRUE
#>     file: TRUE
#>     seed: TRUE 
#>   packages:
#>     geotargets
#>     targets
#>     stats
#>     graphics
#>     grDevices
#>     utils
#>     datasets
#>     methods
#>     base 
#>   library:
#>     NULL
#> $rast_split
#> <tar_pattern> 
#>   name: rast_split 
#>   description:  
#>   command:
#>     `terra::rast`(rast_split_tile) 
#>   pattern:
#>     map(rast_split_tile) 
#>   format: format_custom&read=ZnVuY3Rpb24gKHBhdGgpIAp0ZXJyYTo6cmFzdChwYXRoKQ&write=ZnVuY3Rpb24gKG9iamVjdCwgcGF0aCkgCnsKICAgIHRlcnJhOjp3cml0ZVJhc3RlcihvYmplY3QsIHBhdGgsIGZpbGV0eXBlID0gU3lzLmdldGVudigiR0VPVEFSR0VUU19HREFMX1JBU1RFUl9EUklWRVIiKSwgCiAgICAgICAgb3ZlcndyaXRlID0gVFJVRSwgZ2RhbCA9IHN0cnNwbGl0KFN5cy5nZXRlbnYoIkdFT1RBUkdFVFNfR0RBTF9SQVNURVJfQ1JFQVRJT05fT1BUSU9OUyIsIAogICAgICAgICAgICB1bnNldCA9ICI7IiksICI7IilbWzFdXSkKfQ&marshal=ZnVuY3Rpb24gKG9iamVjdCkgCnRlcnJhOjp3cmFwKG9iamVjdCk&unmarshal=ZnVuY3Rpb24gKG9iamVjdCkgCnRlcnJhOjp1bndyYXAob2JqZWN0KQ&convert=&copy=&repository= 
#>   repository: local 
#>   iteration method: list 
#>   error mode: stop 
#>   memory mode: persistent 
#>   storage mode: main 
#>   retrieval mode: main 
#>   deployment mode: main 
#>   priority: 0 
#>   resources:
#>     custom_format: <environment> 
#>   cue:
#>     mode: thorough
#>     command: TRUE
#>     depend: TRUE
#>     format: TRUE
#>     repository: TRUE
#>     iteration: TRUE
#>     file: TRUE
#>     seed: TRUE 
#>   packages:
#>     geotargets
#>     targets
#>     stats
#>     graphics
#>     grDevices
#>     utils
#>     datasets
#>     methods
#>     base 
#>   library:
#>     NULL
```

``` r

tar_script({
    library(targets)
    library(geotargets)
    
    list(
        tar_terra_rast(
            my_map,
            terra::rast(system.file("ex/elev.tif", package="terra"))
        ),
        tar_terra_tiles(
            name = rast_split,
            raster = my_map,
            template = terra::rast(ncols = 2, nrows = 2),
            tiles_dir = "tiles_test"
        )
    )
})
tar_manifest()
#> # A tibble: 3 × 3
#>   name            command                                                pattern
#>   <chr>           <chr>                                                  <chr>  
#> 1 rast_split_tile "make_tiles(raster = raster, template = template, til… <NA>   
#> 2 my_map          "terra::rast(system.file(\"ex/elev.tif\", package = \… <NA>   
#> 3 rast_split      "`terra::rast`(rast_split_tile)"                       map(ra…
```

``` r
targets::tar_make()
#> ▶ dispatched target rast_split_tile
#> ✖ errored target rast_split_tile
#> ✖ errored pipeline [0.127 seconds]
#> Error:
#> ! Error running targets::tar_make()
#> Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
#> Debugging guide: https://books.ropensci.org/targets/debugging.html
#> How to ask for help: https://books.ropensci.org/targets/help.html
#> Last error message:
#>     could not find function "make_tiles"
#> Last error traceback:
#>     .handleSimpleError(function (condition)  {     state$error <- build_mess...
#>     h(simpleError(msg, call))
```

<sup>Created on 2024-05-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

2024-05-24 23:05 UTC, Aariq commented
Ok, it is "working" now (not passing check, but there is a test that should work now to give you an idea of what it does).  Here's what the manifest looks like:

``` r
library(targets)
tar_script({
    library(targets)
    library(geotargets)
    # devtools::load_all()
    library(terra)
    list(
        tar_target(
            my_file,
            system.file("ex/elev.tif", package="terra"),
            format = "file"
        ),
        tar_terra_rast(
            my_map,
            terra::rast(my_file)
        ),
        tar_terra_tiles(
            name = rast_split,
            raster = my_map,
            template = terra::rast(ncols = 2, nrows = 2),
            tiles_dir = "tiles_test"
        )
    )
})
targets::tar_manifest(callr_function = NULL)
#> terra 1.7.71
#> # A tibble: 5 × 3
#>   name             command                                               pattern
#>   <chr>            <chr>                                                 <chr>  
#> 1 my_file          "system.file(\"ex/elev.tif\", package = \"terra\")"   <NA>   
#> 2 my_map           "terra::rast(my_file)"                                <NA>   
#> 3 rast_split_tile  "geotargets:::make_tiles(raster = my_map, template =… <NA>   
#> 4 rast_split_files "rast_split_tile"                                     map(ra…
#> 5 rast_split       "rast(rast_split_files)"                              map(ra…
```

<sup>Created on 2024-05-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

2024-06-28 21:17 UTC, Aariq commented
Just pushed a fairly major improvement:
- No longer requires writing out to files outside of `_targets/`
- Now creates just two targets: 
    - an upstream target that is a list of numeric vectors that can be coerced to SpatExtent objects
    - a downstream target that iterates over the list of numeric vectors using them to set the `window()` of the original raster
- Exports two new helper functions, mostly so the command in `tar_manifest()` looks pretty, but also they might be helpful on their own.

2024-07-04 12:42 UTC, njtierney requested changes
Just some small changes, this is looking really nice!

2024-07-04 12:42 UTC, njtierney commented on R/tar_terra_tiles.R
> +    lapply(1:nrow(tile_ext), \(i) tile_ext[i,])
```suggestion
    lapply(seq_len(nrow(tile_ext)), \(i) tile_ext[i,])
```

2024-07-04 12:42 UTC, njtierney commented on tests/testthat/test-tar_terra_tiles.R
Small thing, but all the tests use hyphens to separate the words, can this change to hyphen separated?

2024-07-04 12:42 UTC, njtierney commented on R/tar_terra_tiles.R
> +#' Copy a raster with a window
```suggestion
#' Copy a raster within a window
```

2024-07-04 12:42 UTC, njtierney commented on R/tar_terra_tiles.R
> +#' Create a new SpatRaster object based on an original SpatRaster and a window.
```suggestion
#' Create a new SpatRaster object as specified by a window (area of interest) over the original SpatRaster.
```

2024-07-04 12:42 UTC, njtierney commented on R/tar_terra_tiles.R
> +#' @param window A SpatExtent object
```suggestion
#' @param window A SpatExtent object. The window of interest.
```

2024-07-05 17:41 UTC, Aariq commented on R/tar_terra_tiles.R
> +#' @param ... additional arguments not yet used
This was for consistency with other functions `...` arg and I think it is probably grammatically correct as is, although could be "additional arguments which are not yet used".  Either way, I'll keep it as-is for now and if we want to change it we can change it for all functions in a separate PR.

2024-07-11 05:30 UTC, njtierney commented on R/tar_terra_tiles.R
> +#' @param ... additional arguments not yet used
Yup that makes sense!

2024-07-11 05:31 UTC, njtierney approved these changes
Looks good to me!

2024-07-11 05:31 UTC, njtierney commented on R/tar_terra_tiles.R
> +#' @param window A SpatExtent object
Yup that reads great!

2024-07-11 14:54 UTC, merged